### ISSUE TITLE
Thank you for this great simple sensor setup. 

### ISSUE THREAD

**Issue by red-gee** [MartinVerges/womolin-tanksensor#2]
I like your setup much. 
could you also implement Mqtt ?

**Comment by MartinVerges** [comment]
Yes, i currently learn BLE and write a android app for it. Mqtt will be next, and easy to implement.

**Comment by MartinVerges** [comment]
Sorry the BLE stuff took me way longer than expected. I reworked the UI a bit and can now add MQTT. Do you have any special requirements or needs? Otherwise I would just send the current level to a MQTT broker.

**Comment by MartinVerges** [comment]
I just pushed an update including support for mqtt. It's not yet finished and mostly untested, but should already work. Please let me know if you encounter problems with it.

**Comment by MartinVerges** [comment]
I pushed another update to it. Now more settings like user/pass are available and it's now working with my test mqtt broker. I would therefore close it as it's fully operational in my believe. Any objections?
