### ISSUE TITLE
Höhenausgleich

### ISSUE THREAD

**Issue by Maik2016** [MartinVerges/womolin-tanksensor#3]
Hallo,

ich habe den Sensor ausprobiert, dabei ist mir aufgefallen, das beim Höhenwechsel die Werte sich Ändern, d.h. es würde den Richtigen Füllstand nur Anzeigen auf der Höhe bzw. Luftdruck wo Kalibriert wurde.  Ich konnte es jetzt nur auf geringen Höhenunterschied Beobachten.
Kann das jemand Bestätigen ?  GGF. könnte man mit einem BMP280 das ganze Kompensieren indem man den Vorherrschenden Luftdruck bei der Kalibrierung mit aufnimmt und immer dagegen Abgleicht.

**Comment by MartinVerges** [comment]
Hallo,

da es sich um einen Differenzdruck Sensor handelt, sollte dies nicht auftreten, da die Höhe auf beiden Seiten den gleichen Druckunterschied verursacht.

Ich hatte in einem früheren Prototypen einen BMP Sensor und einen Drucksensor im Einsatz, jedoch hat dies zu erheblichen Abweichungen geführt.

Kannst du den Test den du gemacht hast genauer beschreiben?

Ich bin die letzten 4 Tage unterwegs gewesen und habe dabei ca. 400-500 Höhenmeter gehabt. Eine solche Abweichung habe ich jedoch nicht wahrgenommen. Was jedoch in meinem relativ breiten Tank massive Auswirkungen hat, ist die Neigung des Fahrzeugs. Da diese den Druck durch die größer werdenden Wassersäule verändert.

Grüße
Martin

PS: wir können gerne mal einen Video call machen und sprechen.

**Comment by Maik2016** [comment]
Hallo,
Ich hatte auch so ca. 200m Höhenunterschied, es könnte auch am Schräg stehen gelegen haben, das muss ich noch mal testen, daher die Idee einen 2 Sensor als Umgebungsdruck Sensor zu verwenden.

Werde dich mal über Telegramm kontaktieren.
Vg.
Maik

**Comment by MartinVerges** [comment]
Ich habe aktuell das Modell mit eine kleinen 60 cent Pumpe am laufen. Das funktioniert bei jeder höhe und das Rohr lässt sich neu mit dem Umgebungsdruck befüllen. Soweit wäre das eine Funktionierende Lösung die zu immer gleichen soliden und genauen Messwerten führt. Ganz happy bin ich damit leider nicht, weil ich eigentlich auf den Komplexitätsgrad verzichten würde!
